export { Footer as LandingFooter } from '@/components/layout/Footer'
export { BrowseProjectsSection } from '@/components/sections/BrowseProjectsSection'
export { ComingLaterSection } from '@/components/sections/ComingLaterSection'
export { FeaturedProjectsSection as FeaturedBuildsSection } from '@/components/sections/FeaturedProjectsSection'
export { HeroSection } from '@/components/sections/HeroSection'
export { SubmitProjectSection } from '@/components/sections/SubmitProjectSection'
